version: '2'
services:
  kafka:
    image: confluent/kafka:0.9.0.0-cp1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=<YOUR_HOST_IP>
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka_local
  zookeeper:
    image: confluent/zookeeper
    ports:
        - "2181:2181"
    container_name: zookeeper_local
  elk:
    build: .
    image: elk_kafka:latest
    depends_on:
        - kafka
        - zookeeper
    ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
        - "5000:5000"
    container_name: elk_local
